import turtle
Rafael = turtle.Turtle()
Rafael.shape("turtle")
Rafael.color("green")
Rafael.forward(100)
Rafael.right(90)
Rafael.forward(100)
Rafael.right(90)
Rafael.forward(100)
Rafael.right(90)
Rafael.forward(100)